#!/bin/bash
export PATH="$APPDIR/opt/wechat-beta:$PATH"
export LD_LIBRARY_PATH="$APPDIR/opt/wechat-beta:$APPDIR/usr/lib"
export LANG=zh_CN.UTF-8
EXEC="wechat"
if [ $# -eq 1 ]; then
	if [ "$1" = "help"  -o "$1" = "--help"  ]; then
		echo "Run wechat without options"
		echo "Options:"
		echo "    --debug                   return a shell but not wechat"
		echo "    --kill                    to kill wechat process"
		echo "    --install (root required) to install desktop file"
		echo "    --remove  (root required) to remove installation above"
		exit $?
	fi
	if [ "$1" = "--debug" ]; then
		EXEC="bash"
	fi
	if [ "$1" = "--kill"  ]; then
		kill $(ps -e | grep wechat | grep -v "wechat-" | awk '{print $1}')
		exit $?
	fi
	if [ "$1" = "--install" ]; then
		cp $APPDIR/usr/share/applications/wechat.desktop /usr/share/applications
		cp $APPDIR/usr/share/icons/hicolor/256x256/apps/wechat.png /usr/share/icons/hicolor/256x256/apps
		exit $?
	fi
	if [ "$1" = "--remove" ]; then
		rm /usr/share/applications
		rm /usr/share/icons/hicolor/256x256/apps
		rm $APPIMAGE
		exit $?
	fi
fi
# wechat-beta only support xcb
BWRAP_ENV_APPEND="--setenv QT_QPA_PLATFORM xcb "
if [ -z ${QT_IM_MODULE} ]; then
	BWRAP_ENV_APPEND="${BWRAP_ENV_APPEND} --setenv QT_IM_MODULE fcitx"
fi
if [ -z ${GTK_USE_PORTAL} ]; then
	BWRAP_ENV_APPEND="${BWRAP_ENV_APPEND} --setenv GTK_USE_PORTAL 1"
fi
# append user config file
BWRAP_FILE_APPEND=""
if [ -e ~/.config/user-dirs.dirs ]; then
	source ~/.config/user-dirs.dirs
	WECHAT_CFG_DIR=${XDG_DOCUMENTS_DIR}/xwechat_files
	mkdir -p ${WECHAT_CFG_DIR}
	BWRAP_FILE_APPEND="${BWRAP_FILE_APPEND} --bind ${XDG_DESKTOP_DIR}   ${XDG_DESKTOP_DIR}   "
	BWRAP_FILE_APPEND="${BWRAP_FILE_APPEND} --bind ${XDG_DOCUMENTS_DIR} ${XDG_DOCUMENTS_DIR} "
	BWRAP_FILE_APPEND="${BWRAP_FILE_APPEND} --bind ${XDG_DOWNLOAD_DIR}  ${XDG_DOWNLOAD_DIR}  "
	BWRAP_FILE_APPEND="${BWRAP_FILE_APPEND} --bind ${WECHAT_CFG_DIR}    $HOME/xwechat_files  "
else
	echo ">>>>> WARNING: no xdg config file (~/.config/user-dirs.dirs) found."
	echo ">>>>> YOU SHOULD CONFIG IT but now wechat will try continue to run."
fi
FONT1=$HOME/.cache/fontconfig
FONT2=$HOME/.config/fontconfig
if [ -e ${FONT1} ]; then
	BWRAP_FILE_APPEND="${BWRAP_FILE_APPEND} --bind ${FONT1}             ${FONT1}             "
fi
if [ -e ${FONT2} ]; then
	BWRAP_FILE_APPEND="${BWRAP_FILE_APPEND} --bind ${FONT2}             ${FONT2}             "
fi
mkdir -p $HOME/.xwechat
bwrap --die-with-parent                                                   \
	--ro-bind  /                                /                         \
	--tmpfs    /sys  --tmpfs /home              --tmpfs /etc --proc /proc \
	--tmpfs    /run  --tmpfs /usr/lib           --tmpfs /tmp --dev  /dev  \
	--ro-bind  $APPDIR                          $APPDIR                   \
	--ro-bind  $APPDIR/etc/os-release           /etc/os-release           \
	--ro-bind  $APPDIR/etc/lsb-release          /etc/lsb-release          \
	--ro-bind  $APPDIR/etc/.kyact               /etc/.kyact               \
	--ro-bind  $APPDIR/etc/LICENSE              /etc/LICENSE              \
	--ro-bind  /etc/alternatives                /etc/alternatives         \
	--ro-bind  /etc/fonts                       /etc/fonts                \
	--ro-bind  /etc/hostname                    /etc/hostname             \
	--ro-bind  /etc/hosts                       /etc/hosts                \
	--ro-bind  /etc/ld.so.cache                 /etc/ld.so.cache          \
	--ro-bind  /etc/localtime                   /etc/localtime            \
	--ro-bind  /etc/passwd                      /etc/passwd               \
	--ro-bind  /etc/resolv.conf                 /etc/resolv.conf          \
	--ro-bind  $APPDIR/usr/lib/libactivation.so /usr/lib/libactivation.so \
	--ro-bind  /usr/lib/x86_64-linux-gnu        /usr/lib/x86_64-linux-gnu \
	--ro-bind  /usr/lib/udev                    /usr/lib/udev             \
	--ro-bind  /run/user/$UID                   /run/user/$UID            \
	--bind     $HOME/.xwechat                   $HOME/.xwechat            \
	${BWRAP_FILE_APPEND}                                                  \
	${BWRAP_ENV_APPEND}                                                   \
	${EXEC}
# refer: https://blog.lilydjwg.me/2021/8/12/using-bwrap.215869.html
# refer: https://github.com/lfift/wechat-beta-bwrap/blob/main/wechat.sh
